# service configuration
spring:
  application:
    name: greeting-service
server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka

# properties
hello-service:
  usrname: Victoria